[versions]
hamcrest = "3.0"
junit5 = "6.0.1"
kotlin-jvm = "2.2.21"
sonarqube-plugin = "7.1.0.6387"
struts2 = "7.1.1"

[libraries]
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
struts2-core = { group = "org.apache.struts", name = "struts2-core", version.ref = "struts2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
sonarqube-plugin = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }
